version: '3.7'

services:
  postgresql-master:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=admin
      - ALLOW_EMPTY_PASSWORD=yes

  postgresql-slave:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes

  backend:
    build: ./Backend
    restart: always
    container_name: backend_container
    volumes:
      - ./Backend/.env:/usr/src/app/.env
    ports:
      - "1337:1337"
    depends_on:
      - postgresql-master
      - postgresql-slave

  front:
    build:
      context: ./Front/
      target: production
    restart: always
    container_name: Front_container
    ports:
      - "80:80"
    volumes:
      - ./Front/default.conf:/etc/nginx/conf.d/default.conf
      - ./Front/nginx.conf:/etc/nginx/nginx.conf

  admin:
    build:
      context: ./Admin/
      target: production
    restart: always
    container_name: Front_container
    ports:
      - "3006:80"
    volumes:
      - ./Front/default.conf:/etc/nginx/conf.d/default.conf
      - ./Front/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgresql_master_data:
    driver: local